<a href="https://colab.research.google.com/github/ary-puraskar/Combined-Cycle-Power-Plant/blob/main/Combined_Cycle_Power_Plant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries


In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.18.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
df=pd.read_excel('Folds5x2_pp.xlsx')
X=df.iloc[:,:-1].values
Y=df.iloc[:,-1].values


In [4]:
print(X)
print(Y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [6]:
nn=tf.keras.models.Sequential()


### Adding the input layer and the first hidden layer

In [7]:
nn.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [8]:
nn.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [9]:
nn.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [10]:
nn.compile(optimizer='adam',loss='mean_squared_error')

### Training the ANN model on the Training set

In [11]:
nn.fit(X_train,Y_train,batch_size=32, epochs=100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1083.9988
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 140.4084
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 116.2294
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 86.1050
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 65.6054
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 48.1793
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 38.8002
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 34.8839
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 33.4937
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 31.6720
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 31.2097
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 31.6873
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 31.4698
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 30.8924
Epoch 15/100
240/240 ━━━━

### Predicting the results of the Test set

In [14]:
y_pred=nn.predict(X_test)
np.set_printoptions(precision=2)
y_pred=y_pred.reshape(len(y_pred),1)
Y_test=Y_test.reshape(len(Y_test),1)
print(np.concatenate((y_pred,Y_test),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 
[[432.99 431.23]
 [464.05 460.01]
 [467.55 461.14]
 ...
 [474.79 473.26]
 [441.49 438.  ]
 [460.72 463.28]]
